"""
Live trade executor.

JOB:    Real order placement via kalshi.py.
        All orders go to Kalshi's actual API (demo or production).

GUARDS (both must be active):
    1. LIVE_TRADING=true in .env
    2. --live flag passed at CLI

GUARD (first live run):
    Prints giant warning banner, requires interactive "CONFIRM" input.

DOES NOT:
    - Bypass kill switch under any circumstance
    - Call live.py from paper mode
    - Know about strategy or sizing logic
"""

from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.platforms.kalshi import KalshiClient, KalshiAPIError, Market, OrderBook
from src.strategies.base import Signal
from src.db import DB

logger = logging.getLogger(__name__)

_FIRST_RUN_CONFIRMED = False  # module-level flag, reset on restart

# ── Auto-discovered guards (data/auto_guards.json) ────────────────────────
# Generated by scripts/auto_guard_discovery.py — loaded once at module import.
# These supplement the hardcoded IL guards below without requiring code changes.
# Run `python3 scripts/auto_guard_discovery.py` to refresh before restart.
_AUTO_GUARDS_PATH = Path(__file__).parent.parent.parent / "data" / "auto_guards.json"


def _load_auto_guards() -> list[dict]:
    """Load auto-discovered guards from data/auto_guards.json. Returns [] if not found."""
    if not _AUTO_GUARDS_PATH.exists():
        return []
    try:
        with open(_AUTO_GUARDS_PATH) as f:
            data = json.load(f)
        guards = data.get("guards", [])
        if guards:
            logger.info(
                "[live] Loaded %d auto-discovered guard(s) from %s",
                len(guards), _AUTO_GUARDS_PATH.name,
            )
        return guards
    except (json.JSONDecodeError, KeyError, OSError) as e:
        logger.warning("[live] Failed to load auto_guards.json: %s — continuing without", e)
        return []


_AUTO_GUARDS: list[dict] = _load_auto_guards()
# NOTE: This is an ADDITIONAL guard to the main.py CONFIRM prompt.
# main.py prompts at startup; this prompts at first actual order placement.
# Both are intentional — defense-in-depth for real money operations.

# ── Execution-time price guard constants ──────────────────────────────────
# Guard fires AFTER fetching the live orderbook price, immediately before
# placing the order. Protects against HFT repricing in the 0.1-1s asyncio gap
# between signal generation and order placement (observed: fill at 84¢ session 37).
_EXECUTION_MIN_PRICE_CENTS: int = 35
_EXECUTION_MAX_PRICE_CENTS: int = 65
_EXECUTION_MAX_SLIPPAGE_CENTS: int = 10

# ── Sniper per-window correlated risk limits ──────────────────────────────────
# Prevents simultaneous bets across multiple assets in the same 15-min window.
# Root cause S95: 08:00-08:46 UTC crypto dump hit BTC+ETH+XRP simultaneously,
# 3-4 concurrent ~20 USD losses per correlated window (-58 USD in one window).
_SNIPER_MAX_BETS_PER_WINDOW: int = 2
_SNIPER_MAX_USD_PER_WINDOW: float = 30.0


async def execute(
    signal: Signal,
    market: Market,
    orderbook: OrderBook,
    trade_usd: float,
    kalshi: KalshiClient,
    db: DB,
    *,
    live_confirmed: bool = False,
    strategy_name: str = "unknown",
    price_guard_min: int = _EXECUTION_MIN_PRICE_CENTS,
    price_guard_max: int = _EXECUTION_MAX_PRICE_CENTS,
    post_only: bool = False,
    expiration_ts: Optional[int] = None,
    max_slippage_cents: Optional[int] = None,
) -> Optional[dict]:
    """
    Place a real order on Kalshi.

    Args:
        signal:          The trading signal from the strategy
        market:          Current market snapshot
        orderbook:       Current order book
        trade_usd:       Dollar amount to spend (from sizing module)
        kalshi:          Authenticated KalshiClient
        db:              Database for recording the trade
        live_confirmed:  Must be True — set by main.py after first-run confirmation
        strategy_name:   Strategy name saved to DB (e.g. "btc_lag_v1", "btc_drift_v1")
        price_guard_min: Lower bound for YES-equivalent execution price guard (default 35).
                         Override with 1 for expiry_sniper, which operates at 87-99¢.
        price_guard_max: Upper bound for YES-equivalent execution price guard (default 65).
                         Override with 99 for expiry_sniper, which operates at 87-99¢.
        post_only:       If True, order is maker-only. Rejected if it would cross
                         the spread and fill as taker. Saves ~75% on fees for drift.
        expiration_ts:   Unix timestamp when maker order auto-cancels if unfilled.

    Returns:
        Trade record dict on success, None on failure.
    """
    global _FIRST_RUN_CONFIRMED

    # ── Guard 1: env var ─────────────────────────────────────────────
    if os.getenv("LIVE_TRADING", "false").lower() != "true":
        raise RuntimeError(
            "LIVE_TRADING env var is not 'true'. "
            "Set it in .env and restart with --live flag."
        )

    # ── Guard 2: CLI flag ─────────────────────────────────────────────
    if not live_confirmed:
        raise RuntimeError(
            "live_confirmed=False. Pass --live at CLI and confirm the warning prompt."
        )

    # ── Guard 3: First-run confirmation ──────────────────────────────
    if not _FIRST_RUN_CONFIRMED:
        _print_live_warning()
        confirmation = input("Type CONFIRM to proceed with live trading: ").strip()
        if confirmation != "CONFIRM":
            logger.warning("Live trading not confirmed — aborting")
            return None
        _FIRST_RUN_CONFIRMED = True
        logger.info("Live trading confirmed by operator")

    # ── Determine fill price ──────────────────────────────────────────
    price_cents = _determine_limit_price(signal.side, market, orderbook)
    if price_cents is None:
        logger.warning("[live] Cannot determine limit price for %s — skip", signal.ticker)
        return None

    if not (1 <= price_cents <= 99):
        logger.warning("[live] Unreasonable limit price %d¢ — skip", price_cents)
        return None

    # ── Fee-floor guard: block 99c/1c raw prices ──────────────────────────
    # At 99c (either YES or NO side), gross margin = 1c/contract = near-zero net.
    # S72 incident: NO@99c slips through YES-equiv guard because 100-99=1c ∈ [1,99].
    # Explicitly block raw price at boundary to prevent execution at fee-floor prices.
    if price_cents >= 99 or price_cents <= 1:
        logger.info(
            "[live] Execution price %d¢ at fee-floor boundary — skip (no net margin)",
            price_cents,
        )
        return None

    # ── Sniper per-window correlated risk guard ───────────────────────────────
    # Cap simultaneous sniper bets across assets in the same 15-min window.
    # "26MAR170415-15" is the window shared by KXBTC15M-26MAR170415-15, KXETH15M-..., etc.
    if strategy_name == "expiry_sniper_v1":
        _window = signal.ticker.split("-", 1)[1] if "-" in signal.ticker else signal.ticker
        _window_count, _window_usd = db.count_sniper_bets_in_window(_window)
        if _window_count >= _SNIPER_MAX_BETS_PER_WINDOW:
            logger.info(
                "[live] Sniper window cap: %d/%d bets already in window %s — skip %s",
                _window_count, _SNIPER_MAX_BETS_PER_WINDOW, _window, signal.ticker,
            )
            return None
        if _window_usd >= _SNIPER_MAX_USD_PER_WINDOW:
            logger.info(
                "[live] Sniper window USD cap: %.2f/%.2f USD already in window %s — skip %s",
                _window_usd, _SNIPER_MAX_USD_PER_WINDOW, _window, signal.ticker,
            )
            return None

    # ── Negative-EV bucket guard: 96c, 97c-NO, 98c-NO ───────────────────────
    # These buckets are structurally unprofitable based on live bet history:
    #   96c both sides: 31 bets, 93.5% WR, -22.44 USD (needs 96%+ to break even)
    #   97c NO-side:    13 bets, 92.3% WR, -15.03 USD (needs 97%+ to break even)
    #   97c YES-side:   11 bets, 100% WR,   +2.90 USD -- profitable, NOT blocked
    #   98c NO-side:    28 bets, 92.9% WR, -25.54 USD (needs 98%+ to break even)
    #   98c YES-side:   20 bets, 100% WR,   +3.02 USD -- profitable, NOT blocked
    # Validated S74/S75/S78. Revisit at 200+ bets per price level per side.
    if price_cents == 96:
        logger.info(
            "[live] Execution price 96c -- both sides historically negative EV "
            "(93.5%% WR at 31 bets, needs >=96%% to break even) -- skip",
        )
        return None
    if price_cents == 97 and signal.side == "no":
        logger.info(
            "[live] Execution price 97c NO-side -- historically negative EV "
            "(92.3%% WR at 13 bets, needs >=97%% to break even) -- skip",
        )
        return None
    if price_cents == 98 and signal.side == "no":
        logger.info(
            "[live] Execution price 98c NO-side -- historically negative EV "
            "(92.9%% WR at 28 bets, needs >=98%% to break even) -- skip",
        )
        return None

    # ── Per-asset structural loss guards (S81) ────────────────────────────
    # XRP and SOL have higher intra-window volatility than BTC/ETH, causing
    # specific price buckets to fall structurally below break-even WR.
    # IL-10A: XRP YES@94c — 15 bets, 93.3% WR, need 94.9% break-even, -9.09 USD
    if "KXXRP" in signal.ticker and price_cents == 94 and signal.side == "yes":
        logger.info(
            "[live] KXXRP YES@94c -- structurally negative EV "
            "(93.3%% WR at 15 bets, needs 94.9%% to break even) -- skip",
        )
        return None
    # IL-20: XRP YES@95c — 10 bets, 90.0% WR, need 95.0% break-even, -14.27 USD
    # SOL/BTC/ETH YES@95c remain profitable (100% WR). XRP only.
    # Confirmed S88 2026-03-16: loss at KXXRP15M-26MAR160415-15 triggered analysis.
    if "KXXRP" in signal.ticker and price_cents == 95 and signal.side == "yes":
        logger.info(
            "[live] KXXRP YES@95c -- structurally negative EV "
            "(90.0%% WR at 10 bets, needs 95.0%% to break even) -- skip",
        )
        return None

    # IL-10B: XRP YES@97c — 6 bets, 83.3% WR, need 98.0% break-even, -18.04 USD
    if "KXXRP" in signal.ticker and price_cents == 97 and signal.side == "yes":
        logger.info(
            "[live] KXXRP YES@97c -- structurally negative EV "
            "(83.3%% WR at 6 bets, needs 98.0%% to break even, terrible R/R) -- skip",
        )
        return None
    # IL-10C: SOL YES@94c — 12 bets, 91.7% WR, need 94.9% break-even, -7.28 USD
    if "KXSOL" in signal.ticker and price_cents == 94 and signal.side == "yes":
        logger.info(
            "[live] KXSOL YES@94c -- structurally negative EV "
            "(91.7%% WR at 12 bets, needs 94.9%% to break even) -- skip",
        )
        return None
    # IL-19: SOL YES@97c — 8 bets, 87.5% WR, need 97.0% break-even, -17.18 USD
    # BTC/ETH YES@97c remain profitable (100% WR). SOL only.
    # Confirmed S88 2026-03-16: loss at KXSOL15M-26MAR160200-00 triggered analysis.
    if "KXSOL" in signal.ticker and price_cents == 97 and signal.side == "yes":
        logger.info(
            "[live] KXSOL YES@97c -- structurally negative EV "
            "(87.5%% WR at 8 bets, needs 97.0%% to break even) -- skip",
        )
        return None

    # IL-21: XRP NO@92c — 4 bets, 75.0% WR, need 92.0% break-even, -15.33 USD
    # Asymmetric payout: wins ~1.40 USD, losses ~19 USD. Structurally unrecoverable.
    # Pattern: NO@91c=100% WR, NO@92c=75% WR, NO@93c+=100% WR. 92c is the bad bucket.
    # Confirmed S92 2026-03-17: loss at KXXRP15M-26MAR170000 triggered analysis.
    if "KXXRP" in signal.ticker and price_cents == 92 and signal.side == "no":
        logger.info(
            "[live] KXXRP NO@92c -- structurally negative EV "
            "(75.0%% WR at 4 bets, needs 92.0%% to break even) -- skip",
        )
        return None

    # IL-22: SOL NO@92c — 3 bets, 67.0% WR, need 92.0% break-even, -12.97 USD
    # Same asymmetric payout pattern as XRP NO@92c (IL-21): wins ~1.40 USD, losses ~18 USD.
    # SOL NO@91c=100% WR, NO@92c=67% WR, NO@93c+=100% WR. Same per-asset volatility notch.
    # Confirmed S94 2026-03-17: guard added proactively after bucket analysis (n=3 but math is clear).
    if "KXSOL" in signal.ticker and price_cents == 92 and signal.side == "no":
        logger.info(
            "[live] KXSOL NO@92c -- structurally negative EV "
            "(67.0%% WR at 3 bets, needs 92.0%% to break even) -- skip",
        )
        return None

    # IL-23: XRP YES@98c — 11 bets, 90.9% WR, need 98.0% break-even, -17.89 USD
    # Pattern: KXXRP YES@94/95/97c already blocked (IL-10A/B/C, IL-20). 98c same structure.
    # Loss math: win=2c, lose=98c per contract. EV = 0.909×2 - 0.091×98 = -7.1c/contract.
    # On 20 USD max bet at 98c: EV ≈ -1.42 USD per bet. Structurally unrecoverable.
    # Confirmed S94 2026-03-17: loss at KXXRP15M-26MAR162230-30 (-19.60 USD) triggered analysis.
    if "KXXRP" in signal.ticker and price_cents == 98 and signal.side == "yes":
        logger.info(
            "[live] KXXRP YES@98c -- structurally negative EV "
            "(90.9%% WR at 11 bets, needs 98.0%% to break even) -- skip",
        )
        return None

    # IL-24: SOL NO@95c — 16 bets, 93.8% WR, need 95.0% break-even, -31.50 USD
    # SOL has higher intra-window volatility than BTC/ETH — same break-even WR but lower actual WR.
    # BTC/ETH/XRP NO@95c are all 100% WR and profitable. SOL NO@95c is structurally below break-even.
    # Loss math: win=5c, lose=95c per contract. EV = 0.938×5 - 0.063×95 = 4.69 - 5.985 = -1.3c/contract.
    # On 20 USD max bet at 95c: EV ≈ -0.27 USD per bet. Cumulative: -31.50 USD over 16 bets.
    # Confirmed S95 2026-03-17 04:05 UTC: loss at KXSOL15M-26MAR170000-00 (-19.95 USD) triggered analysis.
    if "KXSOL" in signal.ticker and price_cents == 95 and signal.side == "no":
        logger.info(
            "[live] KXSOL NO@95c -- structurally negative EV "
            "(93.8%% WR at 16 bets, needs 95.0%% to break even) -- skip",
        )
        return None

    # IL-25: XRP NO@97c — 4 bets, 75.0% WR, need 97.0% break-even, -17.43 USD
    # Loss math: win=3c, lose=97c per contract. EV = 0.75×3 - 0.25×97 = 2.25 - 24.25 = -22c/contract.
    # Pattern: KXXRP NO@98c same structure (IL-26). High-price NO on XRP = structurally negative EV.
    # Confirmed S95 2026-03-17: bucket analysis after KXSOL NO@95c loss triggered full audit.
    if "KXXRP" in signal.ticker and price_cents == 97 and signal.side == "no":
        logger.info(
            "[live] KXXRP NO@97c -- structurally negative EV "
            "(75.0%% WR at 4 bets, needs 97.0%% to break even) -- skip",
        )
        return None

    # IL-26: XRP NO@98c — 5 bets, 80.0% WR, need 98.0% break-even, -18.07 USD
    # Loss math: win=2c, lose=98c per contract. EV = 0.80×2 - 0.20×98 = 1.6 - 19.6 = -18c/contract.
    # Pattern: mirrors KXXRP YES@98c (IL-23). Both sides at 98c are structurally negative on XRP.
    # Confirmed S95 2026-03-17: bucket analysis after KXSOL NO@95c loss triggered full audit.
    if "KXXRP" in signal.ticker and price_cents == 98 and signal.side == "no":
        logger.info(
            "[live] KXXRP NO@98c -- structurally negative EV "
            "(80.0%% WR at 5 bets, needs 98.0%% to break even) -- skip",
        )
        return None

    # IL-27: SOL YES@96c — 3 bets, 67.0% WR, need 96.0% break-even, -18.51 USD
    # Loss math: win=4c, lose=96c per contract. EV = 0.67×4 - 0.33×96 = 2.68 - 31.68 = -29c/contract.
    # n=3 is below preferred threshold but payout asymmetry is extreme — 1 loss wipes 24+ wins.
    # SOL has per-asset volatility notch at this price level (96c) not seen in BTC/ETH/XRP.
    # Confirmed S95 2026-03-17: bucket analysis after KXSOL NO@95c loss triggered full audit.
    if "KXSOL" in signal.ticker and price_cents == 96 and signal.side == "yes":
        logger.info(
            "[live] KXSOL YES@96c -- structurally negative EV "
            "(67.0%% WR at 3 bets, needs 96.0%% to break even) -- skip",
        )
        return None

    # IL-28: XRP NO@94c — 17 bets, 94.1% WR, need 94.0% break-even, -5.29 USD
    # Fee-adjusted break-even ~94.4% → actual WR (94.1%) is below break-even after fees.
    # One loss wipes ~16 wins (win=6c, loss=94c per contract asymmetry).
    # Trigger: trade #3292 2026-03-17 06:17 UTC KXXRP NO@94c -19.74 USD.
    # Pattern matches IL-21/25/26: high-price KXXRP NO = structurally negative EV.
    if "KXXRP" in signal.ticker and price_cents == 94 and signal.side == "no":
        logger.info(
            "[live] KXXRP NO@94c -- structurally negative EV "
            "(94.1%% WR at 17 bets, fees require ~94.4%% to break even) -- skip",
        )
        return None

    # IL-29: BTC YES@88c — 2 bets, 50.0% WR, need 88.0% break-even, -17.93 USD
    # Loss math: win=12c, lose=88c per contract. EV = 0.50×12 - 0.50×88 = -38c/contract.
    # 88c YES is BELOW the normal sniper floor (90c+). One loss wipes ~7 wins.
    # Pattern: extreme-price YES on BTC at below-floor prices = insufficient edge vs required WR.
    # Confirmed S95 2026-03-17 08:05 UTC: loss at KXBTC15M-26MAR170415-15 (-19.36 USD).
    if "KXBTC" in signal.ticker and price_cents == 88 and signal.side == "yes":
        logger.info(
            "[live] KXBTC YES@88c -- structurally negative EV "
            "(50.0%% WR at 2 bets, needs 88.0%% to break even, below 90c floor) -- skip",
        )
        return None

    # IL-30: ETH YES@93c — 9 bets, 88.9% WR, need 93.0% break-even, -10.83 USD
    # Loss math: win=7c, lose=93c per contract. EV = 0.889×7 - 0.111×93 = 6.22 - 10.32 = -4.1c/contract.
    # One loss wipes ~13 wins (1.26 USD each). Trigger: trade #3382 2026-03-17 08:16 UTC -19.53 USD.
    # ETH YES@90-92c and YES@94c+ excluded — only 93c is the loss pocket for ETH.
    if "KXETH" in signal.ticker and price_cents == 93 and signal.side == "yes":
        logger.info(
            "[live] KXETH YES@93c -- structurally negative EV "
            "(88.9%% WR at 9 bets, needs 93.0%% to break even) -- skip",
        )
        return None

    # IL-31: XRP NO@91c — 5 bets, 80.0% WR, need 91.0% break-even, -14.07 USD
    # Loss math: win=9c, lose=91c per contract. EV = 0.80×9 - 0.20×91 = 7.2 - 18.2 = -11c/contract.
    # Trigger: trade #3383 2026-03-17 08:16 UTC KXXRP NO@91c -19.11 USD.
    # KXXRP NO@91c same correlated-loss-window pattern as IL-30 (same 15-min settlement).
    if "KXXRP" in signal.ticker and price_cents == 91 and signal.side == "no":
        logger.info(
            "[live] KXXRP NO@91c -- structurally negative EV "
            "(80.0%% WR at 5 bets, needs 91.0%% to break even) -- skip",
        )
        return None

    # IL-32: BTC NO@91c — 7 bets, 85.7% WR, need 91.0% break-even, -11.27 USD
    # Loss math: win=9c, lose=91c per contract. EV = 0.857×9 - 0.143×91 = 7.71 - 13.0 = -5.3c/contract.
    # 85.7% WR (6W/1L) is below the 91% break-even threshold.
    # Confirmed S95 2026-03-17 08:46 UTC: loss at KXBTC15M-26MAR170445-45 (-19.11 USD).
    if "KXBTC" in signal.ticker and price_cents == 91 and signal.side == "no":
        logger.info(
            "[live] KXBTC NO@91c -- structurally negative EV "
            "(85.7%% WR at 7 bets, needs 91.0%% to break even) -- skip",
        )
        return None

    # ── Auto-discovered guards (data/auto_guards.json) ───────────────────
    # Loaded at module import from scripts/auto_guard_discovery.py output.
    # Each guard: {ticker_contains, price_cents, side, n_bets, win_rate,
    #              break_even_wr, total_loss_usd, discovered_date}
    # These fire AFTER hardcoded IL guards to catch newly discovered negative-EV buckets.
    if strategy_name == "expiry_sniper_v1" and _AUTO_GUARDS:
        for _ag in _AUTO_GUARDS:
            _ticker_match = (
                _ag["ticker_contains"] is None
                or _ag["ticker_contains"] in signal.ticker
            )
            if (
                _ticker_match
                and price_cents == _ag["price_cents"]
                and signal.side == _ag["side"]
            ):
                logger.info(
                    "[live] AUTO-GUARD: %s %s@%dc — %.1f%% WR (need %.1f%% to break even), "
                    "%s USD loss, discovered %s — skip",
                    _ag["ticker_contains"] or "global",
                    signal.side.upper(),
                    _ag["price_cents"],
                    _ag["win_rate"] * 100,
                    _ag["break_even_wr"] * 100,
                    _ag["total_loss_usd"],
                    _ag.get("discovered_date", "unknown"),
                )
                return None

    # ── Sniper execution-time floor (90c minimum, any side) ──────────────
    # Sniper signals generated at 90c+ but asyncio gap can cause slippage to 88-89c.
    # At sub-90c prices the FLB edge is gone — break-even WR is too low vs actual WR.
    # Root cause: KXBTC YES@88c (IL-29) and KXETH NO@89c both fired below the signal floor.
    # Fix: reject ANY sniper execution price below 90c, regardless of side.
    # Does NOT affect drift strategies (they pass strategy_name != "expiry_sniper_v1").
    _SNIPER_EXECUTION_FLOOR_CENTS = 90
    if strategy_name == "expiry_sniper_v1" and price_cents < _SNIPER_EXECUTION_FLOOR_CENTS:
        logger.info(
            "[live] Sniper execution price %d¢ below floor %d¢ (slippage) — skip %s",
            price_cents, _SNIPER_EXECUTION_FLOOR_CENTS, signal.ticker,
        )
        return None

    # ── Sniper execution-time ceiling (95c maximum, any side) ────────────
    # Fee math: at 97c YES, break-even WR = 97.97% (payout = 3c minus ~1% taker fee).
    # Observed WR at 97c YES = 93% across 30 bets (-30.18 USD cumulative).
    # At 98c YES: break-even = 98.99%. Observed = 98% across 62 bets (-9.06 USD).
    # These are structural losses, not bad luck — the fee math makes them impossible to profit.
    # 96c already blocked (IL-10). Ceiling at 95c closes the 97-98c YES bleed for all assets.
    # Does NOT affect drift strategies.
    _SNIPER_EXECUTION_CEILING_CENTS = 95
    if strategy_name == "expiry_sniper_v1" and price_cents > _SNIPER_EXECUTION_CEILING_CENTS:
        logger.info(
            "[live] Sniper execution price %d¢ above ceiling %d¢ (fee bleed) — skip %s",
            price_cents, _SNIPER_EXECUTION_CEILING_CENTS, signal.ticker,
        )
        return None

    # ── Execution-time price guard ────────────────────────────────────────
    # Convert execution price to YES-equivalent for range + slippage checks.
    # Protects against HFT repricing in the asyncio gap after signal generation.
    execution_yes_price = price_cents if signal.side == "yes" else (100 - price_cents)
    signal_yes_price = signal.price_cents if signal.side == "yes" else (100 - signal.price_cents)

    if not (price_guard_min <= execution_yes_price <= price_guard_max):
        logger.warning(
            "[live] Execution price %d¢ (YES-equiv) outside guard %d-%d¢ — rejecting "
            "(signal was %d¢, ticker=%s)",
            execution_yes_price, price_guard_min, price_guard_max,
            signal_yes_price, signal.ticker,
        )
        return None

    slippage_cents = abs(execution_yes_price - signal_yes_price)
    _slip_limit = max_slippage_cents if max_slippage_cents is not None else _EXECUTION_MAX_SLIPPAGE_CENTS
    if slippage_cents > _slip_limit:
        logger.warning(
            "[live] Slippage %d¢ exceeds max %d¢ — rejecting (signal=%d¢, exec=%d¢, ticker=%s)",
            slippage_cents, _slip_limit,
            signal_yes_price, execution_yes_price, signal.ticker,
        )
        return None

    # ── Calculate contracts ────────────────────────────────────────────
    cost_per_contract = price_cents / 100.0
    count = max(1, int(trade_usd / cost_per_contract))
    expected_cost = count * cost_per_contract

    client_order_id = str(uuid.uuid4())

    logger.info(
        "[LIVE] Placing order: BUY %s %d contracts @ %d¢ = $%.2f | %s",
        signal.side.upper(), count, price_cents, expected_cost, signal.ticker,
    )

    # ── Place order ────────────────────────────────────────────────────
    try:
        order = await kalshi.create_order(
            ticker=signal.ticker,
            side=signal.side,
            action="buy",
            count=count,
            order_type="limit",
            yes_price=price_cents if signal.side == "yes" else None,
            no_price=price_cents if signal.side == "no" else None,
            client_order_id=client_order_id,
            post_only=post_only,
            expiration_ts=expiration_ts,
        )
    except KalshiAPIError as e:
        # ── post_only taker fallback ──────────────────────────────────────
        # If post_only=True and Kalshi rejects with "post only cross", the limit
        # price crossed the spread (market moved). The signal is still valid.
        # Retry immediately as taker (post_only=False) to capture the edge.
        # Taker fees (~1.4%) are covered by drift edge (typically 5-15%).
        # S88 2026-03-16: drift strategies generated 50+ missed trades/session
        # from this pattern without fallback.
        _is_post_only_cross = (
            post_only
            and isinstance(e.body, dict)
            and e.body.get("error", {}).get("details") == "post only cross"
        )
        if _is_post_only_cross:
            logger.info(
                "[live] post_only rejected (spread crossed) — retrying as taker for %s",
                signal.ticker,
            )
            try:
                order = await kalshi.create_order(
                    ticker=signal.ticker,
                    side=signal.side,
                    action="buy",
                    count=count,
                    order_type="limit",
                    yes_price=price_cents if signal.side == "yes" else None,
                    no_price=price_cents if signal.side == "no" else None,
                    client_order_id=str(uuid.uuid4()),
                    post_only=False,
                    expiration_ts=expiration_ts,
                )
            except Exception as e2:
                logger.error("[live] Taker retry failed: %s", e2)
                return None
        else:
            logger.error("[live] Order placement failed: %s", e)
            return None
    except Exception as e:
        logger.error("[live] Unexpected error placing order: %s", e, exc_info=True)
        return None

    now_utc = datetime.now(timezone.utc).isoformat()
    logger.info(
        "[LIVE] Order placed: server_id=%s status=%s",
        order.order_id, order.status,
    )

    # ── Canceled order guard ──────────────────────────────────────────────
    # Kalshi cancels orders that cannot be matched (no liquidity, market closing,
    # risk limit). A canceled order must NOT be recorded as a live bet — doing so
    # corrupts calibration data, inflates trade counters, and poisons Brier scores.
    if order.status == "canceled":
        logger.warning(
            "[live] Order canceled by Kalshi — NOT recording as trade: "
            "server_id=%s ticker=%s",
            order.order_id, signal.ticker,
        )
        return None

    # ── Record to DB ──────────────────────────────────────────────────
    trade_id = db.save_trade(
        ticker=signal.ticker,
        side=signal.side,
        action="buy",
        price_cents=price_cents,
        count=count,
        cost_usd=expected_cost,
        strategy=strategy_name,
        edge_pct=signal.edge_pct,
        win_prob=signal.win_prob,
        is_paper=False,
        client_order_id=client_order_id,
        server_order_id=order.order_id,
    )

    return {
        "trade_id": trade_id,
        "client_order_id": client_order_id,
        "server_order_id": order.order_id,
        "ticker": signal.ticker,
        "side": signal.side,
        "action": "buy",
        "price_cents": price_cents,
        "count": count,
        "cost_usd": expected_cost,
        "status": order.status,
        "is_paper": False,
        "timestamp": now_utc,
    }


def _determine_limit_price(
    side: str,
    market: Market,
    orderbook: OrderBook,
) -> Optional[int]:
    """
    Choose a limit price for live order placement.

    Uses orderbook ask price (the real cost to buy).
    Falls back to market snapshot price.
    """
    if side == "yes":
        yes_ask = orderbook.yes_ask()
        if yes_ask and 1 <= yes_ask <= 99:
            return yes_ask
        if 1 <= market.yes_price <= 99:
            return market.yes_price
    elif side == "no":
        no_ask = orderbook.no_ask()
        if no_ask and 1 <= no_ask <= 99:
            return no_ask
        if 1 <= market.no_price <= 99:
            return market.no_price
    return None


def _print_live_warning():
    print()
    print("=" * 64)
    print("  ⚠️   LIVE TRADING MODE — REAL MONEY AT RISK   ⚠️")
    print()
    print("  You are about to place orders on Kalshi's production API.")
    print("  This uses real funds from your Kalshi account.")
    print()
    print("  Kill switch is active — trades are capped at $5/trade.")
    print("  Starting bankroll: see config.yaml (risk.starting_bankroll_usd)")
    print()
    print("  If you see unexpected behavior:")
    print("  1. Let the kill switch trigger (it will halt automatically)")
    print("  2. Or: Ctrl+C → python main.py --reset-killswitch")
    print()
    print("=" * 64)
    print()
